name: openthread
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt-get install -y gcc-9 g++-9 && export CC=gcc-9 CXX=g++-9
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - uses: actions/checkout@v2
    - name: Before install script
      run: .travis/before_install.sh
    - name: Main script
      run: .travis/script.sh
